version: "3.7"

services:
  engine:
    image: node:12.13.0-alpine
    command: node_modules/.bin/http-server . -p 5000 -a 0.0.0.0
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    network_mode: "bridge"
